### PR TITLE
Added github bot

### PR DESCRIPTION
**Pull request by nikriek**

### CODE REVIEW

**Comment by nikriek** [comment]
sdf

**Comment by nikriek** [comment]
t

**Comment by nikriek** [comment]
dfg

**Comment by nikriek** [comment]
dfyg

**Comment by nikriek** [comment]
gdgdgfdggfgddffg

**Comment by nafetswirth** [comment]
Best bot ever

**Comment by nikriek** [comment]
hello

**Comment by nafetswirth** [comment]
ORLY?

**Comment by nikriek** [comment]
Test

**Comment by nikriek** [comment]
Test

**Comment by nafetswirth** [comment]
topkek

**Comment by NicoKnoll** [comment]
blob

**Comment by nikriek** [comment]
haha

**Pull request closed without merging**
